name: greengrow
description: "Insetron Dedetizadora."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  scrollable_positioned_list: ^0.3.5
  flutter_riverpod: ^2.4.9
  firebase_database: ^10.4.11
  firebase_core: ^2.27.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/